language: node_js
node_js:
  - "9.6"

branches:
  only:
    - master

before_script:
#  - npm install -g @angular/cli

script:
#  - ng build
 - git pull

after_success:
 - node server.js

notifications:
  email:
    on_failure: change
    on_success: change
